project:
  type: website
  output-dir: docs

website:
  title: "Question Time Data Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - data.qmd
      - projects.qmd
      - blogs.qmd
      - contact.qmd

format:
  html:
    theme: 
    - yeti
    - custom.scss
    linkcolor: '#000000'
    toc: true

editor: visual

